[build]
builder = "DOCKERFILE"

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

# Configurações de recursos
[deploy.resources]
memory = 512
cpu = 1

